max_chunk_words: 512
overlap_words: 64

generator:
  model: "gemini-2.0-flash"
  class: "GeminiLLM"

validator:
  model: "gemini-2.5-flash"
  class: "GeminiLLM"

prompt_lang: "vi"

data_type: "qna"

time_delay_seconds: 15